version: '3'

services:
  api-tootodo:
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_CONTAINER_URL}
      
  postgres:
    ports:
    - 6500:5432

  pgadmin:
    ports:
      - 5050:80
  
  mongo:
    ports:
      - 6000:27017