version: '3'

services:
  caddy:
    image: caddy/caddy:2.7.6-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - tootodo_network

volumes:
  caddy_data:
  caddy_config:
