name: Build, Test and Deploy to Prod

on:
  push:
    branches:
      - master

env:
  SQLX_OFFLINE: true
  DATABASE_URL: ${{secrets.DATABASE_TEST_URI}}

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.3-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install SQLx CLI
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres

      - name: Run SQLx Database Migrations
        run: sqlx migrate run

      - name: Generate SQLX Prepared Queries
        run: cargo sqlx prepare

      - name: Build and test code
        run: |
          cargo build --verbose
          cargo test --verbose

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker images
        uses: docker/bake-action@v2.3.0
        with:
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy Caddyfile to vps_server
        run: sshpass -v -p '${{ secrets.VPS_PASSWORD }}' scp -o StrictHostKeyChecking=no Caddyfile root@${{ secrets.VPS_IP }}:~

      - name: Copy docker-compose.yml to vps_server
        run: sshpass -v -p '${{ secrets.VPS_PASSWORD }}' scp -o StrictHostKeyChecking=no docker-compose.yml root@${{ secrets.VPS_IP }}:~

      - name: Copy docker-compose.prod.yml to vps_server
        run: sshpass -v -p '${{ secrets.VPS_PASSWORD }}' scp -o StrictHostKeyChecking=no docker-compose.prod.yml root@${{ secrets.VPS_IP }}:~

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            export JWT_MAXAGE=${{ secrets.JWT_MAXAGE }}
            export POSTGRES_USER=${{secrets.POSTGRES_USER}}
            export POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
            export POSTGRES_DB=${{secrets.POSTGRES_DB}}
            export PGADMIN_DEFAULT_EMAIL=${{secrets.PGADMIN_DEFAULT_EMAIL}}
            export PGADMIN_DEFAULT_PASSWORD=${{secrets.PGADMIN_DEFAULT_PASSWORD}}
            export PGADMIN_LISTEN_PORT=${{secrets.PGADMIN_LISTEN_PORT}}

            export CLIENT_ORIGIN = ${{secrets.CLIENT_ORIGIN}}
            export ACCESS_TOKEN_PRIVATE_KEY = ${{secrets.ACCESS_TOKEN_PRIVATE_KEY}}
            export REFRESH_TOKEN_PRIVATE_KEY = ${{secrets.REFRESH_TOKEN_PRIVATE_KEY}}
            export ACCESS_TOKEN_PUBLIC_KEY = ${{secrets.ACCESS_TOKEN_PUBLIC_KEY}}
            export REFRESH_TOKEN_PUBLIC_KEY = ${{secrets.REFRESH_TOKEN_PUBLIC_KEY}}
            export ACCESS_TOKEN_EXPIRED_IN = ${{secrets.ACCESS_TOKEN_EXPIRED_IN}}
            export REFRESH_TOKEN_EXPIRED_IN = ${{secrets.REFRESH_TOKEN_EXPIRED_IN}}
            export ACCESS_TOKEN_MAXAGE = ${{secrets.ACCESS_TOKEN_MAXAGE}}
            export REFRESH_TOKEN_MAXAGE = ${{secrets.REFRESH_TOKEN_MAXAGE}}
            export Google_OAuth_Client_ID = ${{secrets.Google_OAuth_Client_ID}}
            export Google_OAuth_Client_Secret = ${{secrets.Google_OAuth_Client_Secret}}
            export GOOGLE_OAUTH_REDIRECT_URL = ${{secrets.GOOGLE_OAUTH_REDIRECT_URL}}

            docker-compose down
            docker-compose pull
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
